baseURL = '/'
languageCode = 'en-us'
title = 'SWEN 640'

relativeURLs = true
cleanDestinationDir = true

[frontmatter]
date = [":fileModTime", "publishDate", "date", "lastmod"]

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML"]
page = ["HTML"]

[markup.goldmark.renderer]
unsafe = true

[params]
Logo ='se-logo.png'
LogoLink = 'https://www.rit.edu/computing/department-software-engineering'

[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [["$$", "$$"], ["\\[", "\\]"]]
inline = [["\\(", "\\)"]]